#!/usr/bin/env ruby

require 'json'
require 'csv'

FASTA = File.read('sequences/wrkys.fasta')

def create_element(single)
  {
    name: single[:name],
    sequences: [
      {
        proteinChain: {
          count: 1,
          sequence: single[:sequence]
        }
      }
    ],
    modelSeeds: [42],
    dialect: "alphafoldserver",
    version: 1
  }
end

def entries_from_file(fasta)
  fasta
    .split('>')
    .reject(&:empty?)
    .map do |entry|
      lines = entry.split("\n")
      header = lines.first
      sequence = lines.drop(1).join('')
      name = header.split(/\s+/).first.split('.').first
      { name:, sequence:}
    end
end

entries = entries_from_file(FASTA)
  .map(&method(:create_element))

File.write("wrkys.json", JSON.pretty_generate(entries))
